In [ ]:
import pandas as pd
import numpy as np

## School Information

In [ ]:
file_path = "new_sif_data_table_2021_22prelim_en_march2024.xlsx"

In [ ]:
Schools_df = pd.read_excel(file_path)

In [ ]:
Schools_df.head(3)

,Board Number,Board Name,Board Type,School Number,School Name,School Type,School Special Condition Code,School Level,School Language,Grade Range,...,Change in Grade 6 Writing Achievement Over Three Years,Percentage of Grade 6 Students Achieving the Provincial Standard in Mathematics,Change in Grade 6 Mathematics Achievement Over Three Years,Percentage of Grade 9 Students Achieving the Provincial Standard in Mathematics,Change in Grade 9 Mathematics Achievement Over Three Years,Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt,Change in Grade 10 OSSLT Literacy Achievement Over Three Years,Percentage of School-Aged Children Who Live in Low-Income Households,"Percentage of Students Whose Parents Have No Degree, Diploma or Certificate",Extract Date
0,B28010,Algoma DSB,Pub Dist Sch Brd (E/F),902344,Algoma Education Connection Secondary School,Public,Alternative,Secondary,English,9-12,...,NaN,NaN,NaN,N/D,NaN,N/R,NaN,20,5,03/01/2024
1,B28010,Algoma DSB,Pub Dist Sch Brd (E/F),019186,Anna McCrea Public School,Public,Not applicable,Elementary,English,JK-8,...,NaN,45%,NaN,NaN,NaN,NaN,NaN,10,0,03/01/2024
2,B28010,Algoma DSB,Pub Dist Sch Brd (E/F),043362,Ben R McMullin Public School,Public,Not applicable,Elementary,English,JK-8,...,NaN,38%,NaN,NaN,NaN,NaN,NaN,30,5,03/01/2024

In [ ]:
#Schools and Demographics Dataframe

Columns = Schools_df.columns
print(Columns)

Index(['Board Number', 'Board Name', 'Board Type', 'School Number',
       'School Name', 'School Type', 'School Special Condition Code',
       'School Level', 'School Language', 'Grade Range', 'Building Suite',
       'P.O. Box', 'Street', 'Municipality', 'City', 'Province', 'Postal Code',
       'Phone Number', 'Fax Number', 'School Website', 'Board Website',
       'Enrolment', 'Latitude', 'Longitude',
       'Percentage of Students Whose First Language Is Not English',
       'Percentage of Students Whose First Language Is Not French',
       'Percentage of Students Who Are New to Canada from a Non-English Speaking Country',
       'Percentage of Students Who Are New to Canada from a Non-French Speaking Country',
       'Percentage of Students Receiving Special Education Services',
       'Percentage of Students Identified as Gifted',
       'Percentage of Grade 3 Students Achieving the Provincial Standard in Reading',
       'Change in Grade 3 Reading Achievement Over Three Years',
       'Percentage of Grade 3 Students Achieving the Provincial Standard in Writing',
       'Change in Grade 3 Writing Achievement Over Three Years',
       'Percentage of Grade 3 Students Achieving the Provincial Standard in Mathematics',
       'Change in Grade 3 Mathematics Achievement Over Three Years',
       'Percentage of Grade 6 Students Achieving the Provincial Standard in Reading',
       'Change in Grade 6 Reading Achievement Over Three Years',
       'Percentage of Grade 6 Students Achieving the Provincial Standard in Writing',
       'Change in Grade 6 Writing Achievement Over Three Years',
       'Percentage of Grade 6 Students Achieving the Provincial Standard in Mathematics',
       'Change in Grade 6 Mathematics Achievement Over Three Years',
       'Percentage of Grade 9 Students Achieving the Provincial Standard in Mathematics',
       'Change in Grade 9 Mathematics Achievement Over Three Years',
       'Percentage of Students That Passed the Grade 10 OSSLT on Their First Attempt',
       'Change in Grade 10 OSSLT Literacy Achievement Over Three Years',
       'Percentage of School-Aged Children Who Live in Low-Income Households',
       'Percentage of Students Whose Parents Have No Degree, Diploma or Certificate',
       'Extract Date'],
      dtype='object')

In [ ]:
#School_Location Table

School_location_Columns = ['School Number', 'Board Number' , 'School Name' , 'School Type', 'School Level' , 'Street', 'Municipality', 'City', 'Province', 'Postal Code', 'Fax Number', 'Latitude', 'Longitude', 'Phone Number' , 'School Website']

Schools_all_df = Schools_df[School_location_Columns]

Schools_all_df.head(3)

,School Number,Board Number,School Name,School Type,School Level,Street,Municipality,City,Province,Postal Code,Fax Number,Latitude,Longitude,Phone Number,School Website
0,902344,B28010,Algoma Education Connection Secondary School,Public,Secondary,550 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4J4,705-945-7173,46.53477,-84.3077,705-945-7194,http://www.adsb.on.ca
1,019186,B28010,Anna McCrea Public School,Public,Elementary,250 Mark St,Sault Ste. Marie,Sault Ste Marie,Ontario,P6A3M7,705-945-7221,46.50593,-84.2873,705-945-7106,http://www.adsb.on.ca/sites/schools/amc/defaul...
2,043362,B28010,Ben R McMullin Public School,Public,Elementary,24 Paradise Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B5K2,705-945-7205,46.52455,-84.2980,705-945-7108,http://www.adsb.on.ca/sites/schools/brm/defaul...

In [ ]:
# List of school numbers to be deleted
school_numbers_to_delete = ['SC9205', 'SC9206', 'SC8201', 'SC0302', 'SC0501', 'SC0701', 'SC0403', 'SC9801', 'SC9901', 'SC6103', 'SC0505', 'SC0506', 'SC0802', 'SC0901']

# Delete records with specified school numbers
Schools_all_df = Schools_all_df[~Schools_all_df['School Number'].isin(school_numbers_to_delete)]

# Display the first 3 rows of the updated DataFrame
Schools_all_df.head(3)

,School Number,Board Number,School Name,School Type,School Level,Street,Municipality,City,Province,Postal Code,Fax Number,Latitude,Longitude,Phone Number,School Website
0,902344,B28010,Algoma Education Connection Secondary School,Public,Secondary,550 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4J4,705-945-7173,46.53477,-84.3077,705-945-7194,http://www.adsb.on.ca
1,019186,B28010,Anna McCrea Public School,Public,Elementary,250 Mark St,Sault Ste. Marie,Sault Ste Marie,Ontario,P6A3M7,705-945-7221,46.50593,-84.2873,705-945-7106,http://www.adsb.on.ca/sites/schools/amc/defaul...
2,043362,B28010,Ben R McMullin Public School,Public,Elementary,24 Paradise Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B5K2,705-945-7205,46.52455,-84.2980,705-945-7108,http://www.adsb.on.ca/sites/schools/brm/defaul...

In [ ]:
#Creating a CSV for the school location

Schools_all_df.to_csv('school_data.csv', index=False)

## Board Information

In [ ]:
# Creating the Board Table

Board_Info_Columns = ['Board Number', 'Board Name', 'Board Type','Municipality','Board Website']

Board_Info_df = Schools_df[Board_Info_Columns]

Board_Info_unique_df = Board_Info_df.drop_duplicates(subset=['Board Number'])

Board_Info_unique_df

,Board Number,Board Name,Board Type,Municipality,Board Website
0,B28010,Algoma DSB,Pub Dist Sch Brd (E/F),Sault Ste. Marie,http://www.adsb.on.ca
45,B67202,Algonquin and Lakeshore CDSB,Cath Dist Sch Brd (E/F),Kingston,http://www.alcdsb.on.ca
86,B66010,Avon Maitland DSB,Pub Dist Sch Brd (E/F),Stratford,https://amdsb.ca
131,B80012,Bloorview SA,Provincial/Hospital,Toronto,www.bloorviewschool.ca
132,B66001,Bluewater DSB,Pub Dist Sch Brd (E/F),Owen Sound,http://www.bwdsb.on.ca
...,...,...,...,...,...
4407,B66176,Waterloo Region DSB,Pub Dist Sch Brd (E/F),Waterloo,www.wrdsb.on.ca
4530,B67130,Wellington CDSB,Cath Dist Sch Brd (E/F),Guelph,www.wellingtoncdsb.ca
4552,B67024,Windsor-Essex CDSB,Cath Dist Sch Brd (E/F),Windsor,http://www.wecdsb.on.ca
4596,B67075,York CDSB,Cath Dist Sch Brd (E/F),Markham,http://www.ycdsb.ca
4700,B66095,York Region DSB,Pub Dist Sch Brd (E/F),Richmond Hill,http://www.yrdsb.ca

In [ ]:
#Creating a CSV for School Boards

Board_Info_unique_df.to_csv('board_data.csv', index=False)

## Enrolment 2021-2022

In [ ]:
# Enrolment tables Preparation 2021-2022

Enrolment_file_path = "enrol_grade_2122_en.txt"

Enrolment_df_21_22 = pd.read_csv(Enrolment_file_path, delimiter="|")

Enrolment_df_21_22.head()

,Board Number,Board Name,School Number,School Name,School Type,School Level,School Language,Junior Kindergarten Enrolment,Kindergarten Enrolment,Grade 1 Enrolment,...,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,B28010,Algoma DSB,902344,Algoma Education Connection Secondary School,Public,Secondary,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<10,30,160
1,B28010,Algoma DSB,19186,Anna McCrea Public School,Public,Elementary,English,25,30,20,...,30,25,20,30,15,25,NaN,NaN,NaN,NaN
2,B28010,Algoma DSB,43362,Ben R McMullin Public School,Public,Elementary,English,20,20,15,...,20,25,20,20,20,15,NaN,NaN,NaN,NaN
3,B28010,Algoma DSB,54542,Blind River Public School,Public,Elementary,English,10,15,15,...,20,10,15,20,20,30,NaN,NaN,NaN,NaN
4,B28010,Algoma DSB,490822,Boreal French Immersion Public School,Public,Elementary,English,65,55,65,...,45,40,35,40,40,25,NaN,NaN,NaN,NaN

In [ ]:
#Schools and Demographics Dataframe

Enrolment_Columns = Enrolment_df_21_22.columns

print(Enrolment_Columns)

Index(['Board Number', 'Board Name', 'School Number', 'School Name',
       'School Type', 'School Level', 'School Language',
       'Junior Kindergarten Enrolment', 'Kindergarten Enrolment',
       'Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment',
       'Grade 4 Enrolment', 'Grade 5 Enrolment', 'Grade 6 Enrolment',
       'Grade 7 Enrolment', 'Grade 8 Enrolment', 'Grade 9 Enrolment',
       'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment'],
      dtype='object')

In [ ]:
# Creating the Board Table

Enrolment_by_grade_Columns = ['School Number',
       'School Type', 'School Level',
       'Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment',
       'Grade 4 Enrolment', 'Grade 5 Enrolment', 'Grade 6 Enrolment',
       'Grade 7 Enrolment', 'Grade 8 Enrolment', 'Grade 9 Enrolment',
       'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']

Enrolment_df_21_22 = Enrolment_df_21_22[Enrolment_by_grade_Columns]

Enrolment_df_21_22.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,902344,Public,Secondary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<10,30,160
1,19186,Public,Elementary,20,40,30,25,20,30,15,25,NaN,NaN,NaN,NaN
2,43362,Public,Elementary,15,15,20,25,20,20,20,15,NaN,NaN,NaN,NaN
3,54542,Public,Elementary,15,15,20,10,15,20,20,30,NaN,NaN,NaN,NaN
4,490822,Public,Elementary,65,55,45,40,35,40,40,25,NaN,NaN,NaN,NaN

In [ ]:
# Eliminating the NaN values

Enrolment_df_21_22 = Enrolment_df_21_22.fillna(0)

Enrolment_df_21_22.replace("<",'', regex=True, inplace=True)

Enrolment_df_21_22.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,902344,Public,Secondary,0,0,0,0,0,0,0,0,0,10,30,160
1,19186,Public,Elementary,20,40,30,25,20,30,15,25,0,0,0,0
2,43362,Public,Elementary,15,15,20,25,20,20,20,15,0,0,0,0
3,54542,Public,Elementary,15,15,20,10,15,20,20,30,0,0,0,0
4,490822,Public,Elementary,65,55,45,40,35,40,40,25,0,0,0,0

In [ ]:
# Adding total enrolment for the year

Enrolment_df_21_22[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                      'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                      'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']] = Enrolment_df_21_22[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                                                              'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                                                              'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].apply(pd.to_numeric, errors='coerce')


Enrolment_df_21_22['Total Enrolment'] = Enrolment_df_21_22[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                 'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                 'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].sum(axis=1)

In [ ]:
# Adding the year 2021-2022

Enrolment_df_21_22.insert(1, "Year", "2021-2022")

Enrolment_df_21_22.head()

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
0,902344,2021-2022,Public,Secondary,0,0,0,0,0,0,0,0,0,10,30,160,200
1,19186,2021-2022,Public,Elementary,20,40,30,25,20,30,15,25,0,0,0,0,205
2,43362,2021-2022,Public,Elementary,15,15,20,25,20,20,20,15,0,0,0,0,150
3,54542,2021-2022,Public,Elementary,15,15,20,10,15,20,20,30,0,0,0,0,145
4,490822,2021-2022,Public,Elementary,65,55,45,40,35,40,40,25,0,0,0,0,345

## Enrolment 2020-2021

In [ ]:
# Enrolment tables Preparation Secondary 2020-2021

Enrolment_file_path = "en_school_enrolment_by_grade_2020-2021.txt"
Enrolment_df_20_21=pd.read_csv(Enrolment_file_path, delimiter="|")
Enrolment_df_20_21.head()

,Board Number,Board Name,School Number,School Name,School Type,School Level,School Language,Junior Kindergarten Enrolment,Kindergarten Enrolment,Grade 1 Enrolment,...,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,B28010,Algoma DSB,896873,ADSB 9-12 Virtual School,Public,Secondary,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,<10,<10
1,B28010,Algoma DSB,628718,ADSB JK-8 Virtual School,Public,Elementary,English,<10,<10,<10,...,<10,<10,<10,<10,<10,NaN,NaN,NaN,NaN,NaN
2,B28010,Algoma DSB,902344,Algoma Education Connection Secondary School,Public,Secondary,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,<10,120
3,B28010,Algoma DSB,19186,Anna McCrea Public School,Public,Elementary,English,25,20,30,...,20,15,25,15,30,20,NaN,NaN,NaN,NaN
4,B28010,Algoma DSB,67679,Arthur Henderson Public School,Public,Elementary,English,<10,<10,<10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Creating the Enrolment table for the 20-21 year

Enrolment_by_grade_Columns = ['School Number',
       'School Type', 'School Level',
       'Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment',
       'Grade 4 Enrolment', 'Grade 5 Enrolment', 'Grade 6 Enrolment',
       'Grade 7 Enrolment', 'Grade 8 Enrolment', 'Grade 9 Enrolment',
       'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']

Enrolment_df_20_21 = Enrolment_df_20_21[Enrolment_by_grade_Columns]

Enrolment_df_20_21.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,896873,Public,Secondary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,<10,<10
1,628718,Public,Elementary,<10,<10,<10,<10,<10,<10,<10,NaN,NaN,NaN,NaN,NaN
2,902344,Public,Secondary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,<10,120
3,19186,Public,Elementary,30,25,20,15,25,15,30,20,NaN,NaN,NaN,NaN
4,67679,Public,Elementary,<10,<10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eliminating the NaN values

final_enrolment_2020_2021 = Enrolment_df_20_21.fillna(0)

final_enrolment_2020_2021.replace("<",'', regex=True, inplace=True)

final_enrolment_2020_2021.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,896873,Public,Secondary,0,0,0,0,0,0,0,0,10,10,10,10
1,628718,Public,Elementary,10,10,10,10,10,10,10,0,0,0,0,0
2,902344,Public,Secondary,0,0,0,0,0,0,0,0,10,10,10,120
3,19186,Public,Elementary,30,25,20,15,25,15,30,20,0,0,0,0
4,67679,Public,Elementary,10,10,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Adding total enrolment for the year

final_enrolment_2020_2021[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                      'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                      'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']] = final_enrolment_2020_2021[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                                                              'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                                                              'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].apply(pd.to_numeric, errors='coerce')


final_enrolment_2020_2021['Total Enrolment'] = final_enrolment_2020_2021[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                 'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                 'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].sum(axis=1)

In [ ]:
# Adding the year 2020_2021

final_enrolment_2020_2021.insert(1, "Year", "2020-2021")

final_enrolment_2020_2021.head()

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
0,896873,2020-2021,Public,Secondary,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,10.0,10.0,40.0
1,628718,2020-2021,Public,Elementary,10.0,10.0,10.0,10.0,10.0,10.0,10.0,0.0,0.0,0.0,0.0,0.0,70.0
2,902344,2020-2021,Public,Secondary,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,10.0,120.0,150.0
3,19186,2020-2021,Public,Elementary,30.0,25.0,20.0,15.0,25.0,15.0,30.0,20.0,0.0,0.0,0.0,0.0,180.0
4,67679,2020-2021,Public,Elementary,10.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0

## Enrolment 2019-2020

In [ ]:
# Enrolment tables Preparation Secondary 2019-2020

Enrolment_file_path = "enrol_grade_en_1920.txt"
Enrolment_df_19_20=pd.read_csv(Enrolment_file_path, delimiter="|")
Enrolment_df_19_20.head()

,Board Number,Board Name,School Number,School Name,School Type,School Level,School Language,Junior Kindergarten Enrolment,Kindergarten Enrolment,Grade 1 Enrolment,...,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,B28010,Algoma DSB,902344,Algoma Education Connection Secondary School,Public,Secondary,English,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,30,175
1,B28010,Algoma DSB,19186,Anna McCrea Public School,Public,Elementary,English,20,30,25,...,15,30,15,30,20,<10,NaN,NaN,NaN,NaN
2,B28010,Algoma DSB,67679,Arthur Henderson Public School,Public,Elementary,English,<10,<10,<10,...,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,B28010,Algoma DSB,43362,Ben R McMullin Public School,Public,Elementary,English,15,10,15,...,15,20,15,20,15,<10,NaN,NaN,NaN,NaN
4,B28010,Algoma DSB,54542,Blind River Public School,Public,Elementary,English,15,15,10,...,15,15,25,25,15,30,NaN,NaN,NaN,NaN

In [ ]:
# Creating the Enrolment table for the 19-20 year

Enrolment_by_grade_Columns = ['School Number',
       'School Type', 'School Level',
       'Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment',
       'Grade 4 Enrolment', 'Grade 5 Enrolment', 'Grade 6 Enrolment',
       'Grade 7 Enrolment', 'Grade 8 Enrolment', 'Grade 9 Enrolment',
       'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']

Enrolment_df_19_20 = Enrolment_df_19_20[Enrolment_by_grade_Columns]

Enrolment_df_19_20.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,902344,Public,Secondary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<10,<10,30,175
1,19186,Public,Elementary,25,15,15,30,15,30,20,<10,NaN,NaN,NaN,NaN
2,67679,Public,Elementary,<10,<10,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,43362,Public,Elementary,15,20,15,20,15,20,15,<10,NaN,NaN,NaN,NaN
4,54542,Public,Elementary,10,10,15,15,25,25,15,30,NaN,NaN,NaN,NaN

In [ ]:
# Eliminating the NaN values

final_enrolment_2019_2020 = Enrolment_df_19_20.fillna(0)

final_enrolment_2019_2020.replace("<",'', regex=True, inplace=True)

final_enrolment_2019_2020.head()

,School Number,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
0,902344,Public,Secondary,0,0,0,0,0,0,0,0,10,10,30,175
1,19186,Public,Elementary,25,15,15,30,15,30,20,10,0,0,0,0
2,67679,Public,Elementary,10,10,10,0,0,0,0,0,0,0,0,0
3,43362,Public,Elementary,15,20,15,20,15,20,15,10,0,0,0,0
4,54542,Public,Elementary,10,10,15,15,25,25,15,30,0,0,0,0

In [ ]:
# Adding total enrolment for the year

final_enrolment_2019_2020[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                      'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                      'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']] = final_enrolment_2019_2020[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                                                              'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                                                              'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].apply(pd.to_numeric, errors='coerce')


final_enrolment_2019_2020['Total Enrolment'] = final_enrolment_2019_2020[['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
                                                                 'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
                                                                 'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']].sum(axis=1)

In [ ]:
# Adding the year 2019_2020

final_enrolment_2019_2020.insert(1, "Year", "2019-2020")

final_enrolment_2019_2020.head()

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
0,902344,2019-2020,Public,Secondary,0,0,0,0,0,0,0,0,10,10,30,175.0,225.0
1,19186,2019-2020,Public,Elementary,25,15,15,30,15,30,20,10,0,0,0,0.0,160.0
2,67679,2019-2020,Public,Elementary,10,10,10,0,0,0,0,0,0,0,0,0.0,30.0
3,43362,2019-2020,Public,Elementary,15,20,15,20,15,20,15,10,0,0,0,0.0,130.0
4,54542,2019-2020,Public,Elementary,10,10,15,15,25,25,15,30,0,0,0,0.0,145.0

In [ ]:
# Concatenating the three tables

final_enrolment_df = pd.concat([final_enrolment_2019_2020,final_enrolment_2020_2021,Enrolment_df_21_22])

final_enrolment_df.sample(10)

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
4214,438170,2019-2020,Public,Elementary,10.0,10.0,15.0,15.0,10.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,75.0
1294,295434,2020-2021,Public,Elementary,20.0,20.0,20.0,20.0,25.0,30.0,25.0,25.0,0.0,0.0,0.0,0.0,185.0
1696,328456,2019-2020,Public,Elementary,40.0,25.0,30.0,45.0,35.0,60.0,30.0,25.0,0.0,0.0,0.0,0.0,290.0
3284,410454,2020-2021,Public,Elementary,0.0,0.0,0.0,70.0,75.0,70.0,80.0,80.0,0.0,0.0,0.0,0.0,375.0
281,204986,2019-2020,Public,Elementary,70.0,70.0,65.0,75.0,65.0,65.0,0.0,0.0,0.0,0.0,0.0,0.0,410.0
1223,577669,2021-2022,Public,Elementary,50.0,45.0,45.0,50.0,55.0,55.0,50.0,55.0,0.0,0.0,0.0,0.0,405.0
4613,704245,2020-2021,Catholic,Elementary,50.0,60.0,55.0,45.0,70.0,50.0,55.0,80.0,0.0,0.0,0.0,0.0,465.0
2945,451649,2019-2020,Public,Elementary,40.0,40.0,40.0,45.0,80.0,75.0,80.0,90.0,0.0,0.0,0.0,0.0,490.0
3131,770671,2020-2021,Catholic,Elementary,25.0,40.0,40.0,40.0,50.0,30.0,45.0,30.0,0.0,0.0,0.0,0.0,300.0
4345,743186,2021-2022,Catholic,Elementary,35.0,40.0,30.0,60.0,30.0,40.0,40.0,40.0,0.0,0.0,0.0,0.0,315.0

In [ ]:
final_enrolment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14702 entries, 0 to 4892
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Number       14702 non-null  int64
 1   Year                14702 non-null  object
 2   School Type         14702 non-null  object
 3   School Level        14702 non-null  object
 4   Grade 1 Enrolment   14696 non-null  float64
 5   Grade 2 Enrolment   14696 non-null  float64
 6   Grade 3 Enrolment   14696 non-null  float64
 7   Grade 4 Enrolment   14696 non-null  float64
 8   Grade 5 Enrolment   14696 non-null  float64
 9   Grade 6 Enrolment   14696 non-null  float64
 10  Grade 7 Enrolment   14697 non-null  float64
 11  Grade 8 Enrolment   14697 non-null  float64
 12  Grade 9 Enrolment   14700 non-null  float64
 13  Grade 10 Enrolment  14699 non-null  float64
 14  Grade 11 Enrolment  14700 non-null  float64
 15  Grade 12 Enrolment  14698 non-null  float64
 16  Total Enrolment     14702 non-null  float64
dtypes: float64(13), int64(1), object(3)
memory usage: 2.0+ MB

In [ ]:
final_enrolment_df.isnull().sum()

School Number         0
Year                  0
School Type           0
School Level          0
Grade 1 Enrolment     6
Grade 2 Enrolment     6
Grade 3 Enrolment     6
Grade 4 Enrolment     6
Grade 5 Enrolment     6
Grade 6 Enrolment     6
Grade 7 Enrolment     5
Grade 8 Enrolment     5
Grade 9 Enrolment     2
Grade 10 Enrolment    3
Grade 11 Enrolment    2
Grade 12 Enrolment    4
Total Enrolment       0
dtype: int64

In [ ]:
final_enrolment_df.dropna(inplace=True)

In [ ]:
final_enrolment_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14692 entries, 0 to 4892
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Number       14692 non-null  int64
 1   Year                14692 non-null  object
 2   School Type         14692 non-null  object
 3   School Level        14692 non-null  object
 4   Grade 1 Enrolment   14692 non-null  float64
 5   Grade 2 Enrolment   14692 non-null  float64
 6   Grade 3 Enrolment   14692 non-null  float64
 7   Grade 4 Enrolment   14692 non-null  float64
 8   Grade 5 Enrolment   14692 non-null  float64
 9   Grade 6 Enrolment   14692 non-null  float64
 10  Grade 7 Enrolment   14692 non-null  float64
 11  Grade 8 Enrolment   14692 non-null  float64
 12  Grade 9 Enrolment   14692 non-null  float64
 13  Grade 10 Enrolment  14692 non-null  float64
 14  Grade 11 Enrolment  14692 non-null  float64
 15  Grade 12 Enrolment  14692 non-null  float64
 16  Total Enrolment     14692 non-null  float64
dtypes: float64(13), int64(1), object(3)
memory usage: 2.0+ MB

In [ ]:
# converting all the values to integers

final_enrolment_df[["Grade 1 Enrolment",
"Grade 2 Enrolment",
"Grade 3 Enrolment",
"Grade 4 Enrolment",
"Grade 5 Enrolment",
"Grade 6 Enrolment",
"Grade 7 Enrolment",
"Grade 8 Enrolment",
"Grade 9 Enrolment",
"Grade 10 Enrolment",
"Grade 11 Enrolment",
"Grade 12 Enrolment",
"Total Enrolment"]] = final_enrolment_df[["Grade 1 Enrolment",
"Grade 2 Enrolment",
"Grade 3 Enrolment",
"Grade 4 Enrolment",
"Grade 5 Enrolment",
"Grade 6 Enrolment",
"Grade 7 Enrolment",
"Grade 8 Enrolment",
"Grade 9 Enrolment",
"Grade 10 Enrolment",
"Grade 11 Enrolment",
"Grade 12 Enrolment",
"Total Enrolment"]].astype(int)

final_enrolment_df.sample(10)

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
4510,689661,2021-2022,Catholic,Secondary,0,0,0,0,0,0,0,0,170,170,170,195,705
923,751430,2019-2020,Catholic,Secondary,0,0,0,0,0,0,0,0,260,260,275,255,1050
338,532816,2019-2020,Public,Elementary,0,0,0,0,0,0,20,20,0,0,0,0,40
3008,244996,2020-2021,Public,Elementary,75,65,75,55,45,60,40,35,0,0,0,0,450
4452,1058,2020-2021,Public,Elementary,35,40,30,25,40,40,40,45,0,0,0,0,295
4338,733121,2019-2020,Catholic,Elementary,40,40,50,45,50,50,45,55,0,0,0,0,375
3469,776980,2020-2021,Catholic,Elementary,40,50,45,35,50,30,40,50,0,0,0,0,340
2528,565750,2020-2021,Public,Elementary,55,45,55,75,70,85,80,75,0,0,0,0,540
2641,506613,2019-2020,Public,Elementary,0,0,0,0,0,0,10,10,0,0,0,0,20
4860,597201,2020-2021,Public,Elementary,45,35,50,40,55,55,55,75,0,0,0,0,410

## Extracting the enrolment df

In [ ]:
# Extracting the enrolment data

final_enrolment_df.to_csv("Endrolment_Data.csv", index = False)

## Enrolment for the next five year

In [ ]:
# Reading csv file for enrolment
df = pd.read_csv("enrolment_data_final.csv")

In [ ]:
# Extracting the first year for each row
df["Year"] = df["Year"].str.split("-").str[0]

# Transform the Year column to int
df["Year"] = df["Year"].astype(int)

In [ ]:
# Identify unique schools
unique_schools = df['School Number'].unique()

# Define the range of future years
future_years = range(2022, 2027)

# Create an empty list to store future enrolment data
future_enrolment_data = []

# Iterate over each school to generate predictions
for school in unique_schools:
    # Filter data for the current school
    school_data = df[df['School Number'] == school]

    # Iterate over each grade's enrolment data
    for grade in range(1, 13):

        # Calculate the average growth rate
        grade_column = f'Grade {grade} Enrolment'
        enrolment_growth_rate = school_data[grade_column].pct_change().mean()

        # Assuming the last known year's enrolment is the base for forecasting
        last_known_year = school_data['Year'].max()
        last_year_data = school_data[school_data['Year'] == last_known_year]

        # Get the enrolment for the last known year for the current grade
        last_year_enrolment = last_year_data[grade_column].values[0]

        # Iterate over future years
        for year in future_years:

            # Project future enrolment for the current grade using the average growth rate
            predicted_enrolment = last_year_enrolment * (1 + enrolment_growth_rate)

            # Append the predicted enrolment for the current school, grade, and year
            future_enrolment_data.append({
                'School Number': school,
                'Year': year,
                'Grade': grade,
                'Enrolment': predicted_enrolment
            })

            # Update the last year enrolment for the next iteration
            last_year_enrolment = predicted_enrolment

# Create a DataFrame from the list of future enrolment data
future_df = pd.DataFrame(future_enrolment_data)

<ipython-input-7-fdc91629ea6a>:33: RuntimeWarning: invalid value encountered in scalar multiply
  predicted_enrolment = last_year_enrolment * (1 + enrolment_growth_rate)

In [ ]:
# Pivot the DataFrame to have separate columns for each grade's enrolment
future_df_pivot = future_df.pivot_table(index=['School Number', 'Year'], columns='Grade', values='Enrolment').reset_index()

# Renaming the columns
future_df_pivot.columns = ['School Number', 'Year'] + [f'Grade {grade} Enrolment' if grade else 'Year' for grade in future_df_pivot.columns[2:]]
future_df_pivot.columns.name = None

In [ ]:
# Renaming the future_df_pivot
future_df = future_df_pivot

# Replace infinite values (inf) with NaN
future_df.replace([np.inf, -np.inf], np.nan, inplace=True)

# Drop rows containing NaN values
future_df.fillna(0, inplace=True)

# Dimentioning the Grade columns as integers
columns = ['Grade 1 Enrolment', 'Grade 2 Enrolment', 'Grade 3 Enrolment', 'Grade 4 Enrolment',
           'Grade 5 Enrolment', 'Grade 6 Enrolment', 'Grade 7 Enrolment', 'Grade 8 Enrolment',
           'Grade 9 Enrolment', 'Grade 10 Enrolment', 'Grade 11 Enrolment', 'Grade 12 Enrolment']
for col in columns:
    future_df[col] = pd.to_numeric(future_df[col], errors='coerce').astype(int)

In [ ]:
future_df.sample(10)

,School Number,Year,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment
14320,763659,2022,0,0,0,0,0,0,0,0,263,205,244,252
555,125261,2022,10,10,10,10,10,10,10,10,0,0,0,0
19290,899569,2022,0,0,0,0,0,0,0,0,149,123,117,106
2993,241610,2025,92,27,53,34,22,120,0,0,0,0,0,0
8570,520225,2022,29,33,58,29,53,43,47,57,0,0,0,0
897,139823,2024,16,18,11,26,14,58,33,31,0,0,0,0
13835,750581,2022,12,15,29,15,23,23,12,25,0,0,0,0
10296,612502,2023,58,50,45,55,59,51,0,0,0,0,0,0
9900,595012,2022,88,45,80,76,49,52,83,96,0,0,0,0
10716,683246,2023,45,43,30,19,25,22,44,79,0,0,0,0

In [ ]:
# Extracting the future enrolment data
future_df.to_csv("Future_Enrolment.csv", index = False)

## Graduation

In [ ]:
#Graduation Table

Graduation_file_path = "sbpr_data_table_en_jan2024.xlsx"

Graduation_df = pd.read_excel(Graduation_file_path)

Graduation_df.head()

,Board Number,Board Name,Board Language,Board Type,Region,City,Grade 6 EQAO Reading Results,Progress in Grade 6 EQAO Reading Results,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Four Year Graduation Rate 2018-2019 Grade 9 Cohort,Progress in Four Year Graduation Rate 2018-2019 Grade 9 Cohort
0,B28010,Algoma DSB,English,Public,North Region,Sault Ste Marie,0.78,NaN,0.72,NaN,0.69,-0.02,0.71,-0.08,0.718,0.018,0.760,-0.009,0.709,-0.037
1,B67202,Algonquin and Lakeshore CDSB,English,Roman Catholic,East Region,Napanee,0.78,NaN,0.86,NaN,0.84,0.00,0.87,-0.03,0.880,0.004,0.923,0.015,0.882,-0.014
2,B66010,Avon Maitland DSB,English,Public,West Region,Seaforth,0.84,NaN,0.81,NaN,0.81,0.03,0.78,-0.01,0.810,0.066,0.868,-0.002,0.806,0.013
3,B66001,Bluewater DSB,English,Public,West Region,Chesley,0.76,NaN,0.75,NaN,0.67,-0.01,0.71,-0.01,0.711,0.011,0.824,0.004,0.701,-0.017
4,B67164,Brant Haldimand Norfolk CDSB,English,Roman Catholic,West Region,Brantford,0.85,NaN,0.85,NaN,0.73,-0.08,0.81,-0.01,0.797,-0.038,0.868,-0.018,0.856,0.050

In [ ]:
#Graduation Dataframe

print(Graduation_df.columns)

Index(['Board Number', 'Board Name', 'Board Language', 'Board Type', 'Region ',
       'City', 'Grade 6 EQAO Reading Results',
       'Progress in Grade 6 EQAO Reading Results', 'Grade 10 OSSLT Results',
       'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Five Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Four Year Graduation Rate 2018-2019 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2018-2019 Grade 9 Cohort'],
      dtype='object')

In [ ]:
# Graduation Table

columns_to_drop = ['Board Name',
                   'Board Language',
                   'City',
                   'Grade 6 EQAO Reading Results',
                   'Progress in Grade 6 EQAO Reading Results',
                   ]

Graduation_df = Graduation_df.drop(columns=columns_to_drop)

Graduation_df.head()

,Board Number,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Four Year Graduation Rate 2018-2019 Grade 9 Cohort,Progress in Four Year Graduation Rate 2018-2019 Grade 9 Cohort
0,B28010,Public,North Region,0.72,NaN,0.69,-0.02,0.71,-0.08,0.718,0.018,0.760,-0.009,0.709,-0.037
1,B67202,Roman Catholic,East Region,0.86,NaN,0.84,0.00,0.87,-0.03,0.880,0.004,0.923,0.015,0.882,-0.014
2,B66010,Public,West Region,0.81,NaN,0.81,0.03,0.78,-0.01,0.810,0.066,0.868,-0.002,0.806,0.013
3,B66001,Public,West Region,0.75,NaN,0.67,-0.01,0.71,-0.01,0.711,0.011,0.824,0.004,0.701,-0.017
4,B67164,Roman Catholic,West Region,0.85,NaN,0.73,-0.08,0.81,-0.01,0.797,-0.038,0.868,-0.018,0.856,0.050

In [ ]:
Graduation_df.to_csv("Graduation_to_process", index= False)

In [ ]:
Graduation_to_process_df = pd.read_csv("Graduation_to_process")

In [ ]:
Graduation_to_process_df.head()

,Board Number,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort,Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1
0,B28010,Public,North Region,0.72,NaN,0.69,-0.02,0.71,-0.08,0.718,0.018,0.760,-0.009,0.709,-0.037
1,B67202,Roman Catholic,East Region,0.86,NaN,0.84,0.00,0.87,-0.03,0.880,0.004,0.923,0.015,0.882,-0.014
2,B66010,Public,West Region,0.81,NaN,0.81,0.03,0.78,-0.01,0.810,0.066,0.868,-0.002,0.806,0.013
3,B66001,Public,West Region,0.75,NaN,0.67,-0.01,0.71,-0.01,0.711,0.011,0.824,0.004,0.701,-0.017
4,B67164,Roman Catholic,West Region,0.85,NaN,0.73,-0.08,0.81,-0.01,0.797,-0.038,0.868,-0.018,0.856,0.050

In [ ]:
# Graduation_df columns list
print(Graduation_to_process_df.columns)

Index(['Board Number', 'Board Type', 'Region ', 'Grade 10 OSSLT Results',
       'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Five Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1'],
      dtype='object')

In [ ]:
#Graduation table for 2020-2021
graduation_21_22_df =  Graduation_to_process_df[['Board Number', 'Board Type', "Region ", 'Grade 10 OSSLT Results',
       'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort']]

graduation_21_22_df.insert(1, "Year", "2021-2022")

graduation_21_22_df = graduation_21_22_df.fillna(0)

graduation_21_22_df.head()

,Board Number,Year,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort
0,B28010,2021-2022,Public,North Region,0.72,0.0,0.69,-0.02,0.71,-0.08,0.718,0.018
1,B67202,2021-2022,Roman Catholic,East Region,0.86,0.0,0.84,0.00,0.87,-0.03,0.880,0.004
2,B66010,2021-2022,Public,West Region,0.81,0.0,0.81,0.03,0.78,-0.01,0.810,0.066
3,B66001,2021-2022,Public,West Region,0.75,0.0,0.67,-0.01,0.71,-0.01,0.711,0.011
4,B67164,2021-2022,Roman Catholic,West Region,0.85,0.0,0.73,-0.08,0.81,-0.01,0.797,-0.038

In [ ]:
# graduation_21_22_df columns
print(graduation_21_22_df.columns)

Index(['Board Number', 'Year', 'Board Type', 'Region ',
       'Grade 10 OSSLT Results', 'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort'],
      dtype='object')

In [ ]:
#Extracting Graduation Data 21-22

graduation_21_22_df.to_csv('Graduation_Data_21_22.csv', index=False)

In [ ]:
#Graduation table for 2020-2021


columns_to_drop = ['Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Five Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Five Year Graduation Rate 2017-2018 Grade 9 Cohort']

graduation_22_23_df =  Graduation_to_process_df.drop(columns=columns_to_drop)

graduation_22_23_df.insert(1, "Year", "2022-2023")

graduation_22_23_df = graduation_22_23_df.fillna(0)

graduation_22_23_df.head()

,Board Number,Year,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1
0,B28010,2022-2023,Public,North Region,0.72,0.0,0.69,-0.02,0.71,-0.08,0.709,-0.037
1,B67202,2022-2023,Roman Catholic,East Region,0.86,0.0,0.84,0.00,0.87,-0.03,0.882,-0.014
2,B66010,2022-2023,Public,West Region,0.81,0.0,0.81,0.03,0.78,-0.01,0.806,0.013
3,B66001,2022-2023,Public,West Region,0.75,0.0,0.67,-0.01,0.71,-0.01,0.701,-0.017
4,B67164,2022-2023,Roman Catholic,West Region,0.85,0.0,0.73,-0.08,0.81,-0.01,0.856,0.050

In [ ]:
#Extracting Graduation Data 22-23

graduation_22_23_df.to_csv('Graduation_Data_22_23.csv', index=False)

## Concat the graduation Data

In [ ]:

Graduation_to_process_21_22_df = pd.read_csv("Graduation_Data_21_22.csv")
Graduation_to_process_22_23_df = pd.read_csv("Graduation_Data_22_23.csv")

In [ ]:

print(Graduation_to_process_21_22_df.columns)
Graduation_to_process_21_22_df.head()

Index(['Board Number', 'Year', 'Board Type', 'Region ',
       'Grade 10 OSSLT Results', 'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort'],
      dtype='object')

,Board Number,Year,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort
0,B28010,2021-2022,Public,North Region,0.72,0.0,0.69,-0.02,0.71,-0.08,0.718,0.018
1,B67202,2021-2022,Roman Catholic,East Region,0.86,0.0,0.84,0.00,0.87,-0.03,0.880,0.004
2,B66010,2021-2022,Public,West Region,0.81,0.0,0.81,0.03,0.78,-0.01,0.810,0.066
3,B66001,2021-2022,Public,West Region,0.75,0.0,0.67,-0.01,0.71,-0.01,0.711,0.011
4,B67164,2021-2022,Roman Catholic,West Region,0.85,0.0,0.73,-0.08,0.81,-0.01,0.797,-0.038

In [ ]:
print(Graduation_to_process_22_23_df.columns)
Graduation_to_process_22_23_df.head()

Index(['Board Number', 'Year', 'Board Type', 'Region ',
       'Grade 10 OSSLT Results', 'Progress in Grade 10 OSSLT Results ',
       'Credit Accumulation by the end of Grade 10',
       'Progress in Credit Accumulation by the end of Grade 10',
       'Credit Accumulation by the end of Grade 11',
       'Progress in Credit Accumulation by the end of Grade 11',
       'Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1',
       'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1'],
      dtype='object')

,Board Number,Year,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1
0,B28010,2022-2023,Public,North Region,0.72,0.0,0.69,-0.02,0.71,-0.08,0.709,-0.037
1,B67202,2022-2023,Roman Catholic,East Region,0.86,0.0,0.84,0.00,0.87,-0.03,0.882,-0.014
2,B66010,2022-2023,Public,West Region,0.81,0.0,0.81,0.03,0.78,-0.01,0.806,0.013
3,B66001,2022-2023,Public,West Region,0.75,0.0,0.67,-0.01,0.71,-0.01,0.701,-0.017
4,B67164,2022-2023,Roman Catholic,West Region,0.85,0.0,0.73,-0.08,0.81,-0.01,0.856,0.050

In [ ]:
Graduation_to_process_22_23_df.rename(columns={'Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1': 'Four Year Graduation Rate 2017-2018 Grade 9 Cohort'}, inplace=True)
Graduation_to_process_22_23_df.rename(columns={'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort.1': 'Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort'}, inplace=True)

In [ ]:

final_graduation = pd.concat([Graduation_to_process_21_22_df,Graduation_to_process_22_23_df])
final_graduation.head()

,Board Number,Year,Board Type,Region,Grade 10 OSSLT Results,Progress in Grade 10 OSSLT Results,Credit Accumulation by the end of Grade 10,Progress in Credit Accumulation by the end of Grade 10,Credit Accumulation by the end of Grade 11,Progress in Credit Accumulation by the end of Grade 11,Four Year Graduation Rate 2017-2018 Grade 9 Cohort,Progress in Four Year Graduation Rate 2017-2018 Grade 9 Cohort
0,B28010,2021-2022,Public,North Region,0.72,0.0,0.69,-0.02,0.71,-0.08,0.718,0.018
1,B67202,2021-2022,Roman Catholic,East Region,0.86,0.0,0.84,0.00,0.87,-0.03,0.880,0.004
2,B66010,2021-2022,Public,West Region,0.81,0.0,0.81,0.03,0.78,-0.01,0.810,0.066
3,B66001,2021-2022,Public,West Region,0.75,0.0,0.67,-0.01,0.71,-0.01,0.711,0.011
4,B67164,2021-2022,Roman Catholic,West Region,0.85,0.0,0.73,-0.08,0.81,-0.01,0.797,-0.038

In [ ]:
# Extracting graduation data

final_graduation.to_csv("graduation_data.csv", index= False)

## Table Corrections

In [ ]:
School_path = "school_data.csv"

School_df = pd.read_csv(School_path)

School_df.head()

,School Number,Board Number,School Name,School Type,School Level,Street,Municipality,City,Province,Postal Code,Fax Number,Latitude,Longitude,Phone Number,School Website
0,902344,B28010,Algoma Education Connection Secondary School,Public,Secondary,550 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4J4,705-945-7173,46.53477,-84.3077,705-945-7194,http://www.adsb.on.ca
1,019186,B28010,Anna McCrea Public School,Public,Elementary,250 Mark St,Sault Ste. Marie,Sault Ste Marie,Ontario,P6A3M7,705-945-7221,46.50593,-84.2873,705-945-7106,http://www.adsb.on.ca/sites/schools/amc/defaul...
2,043362,B28010,Ben R McMullin Public School,Public,Elementary,24 Paradise Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B5K2,705-945-7205,46.52455,-84.2980,705-945-7108,http://www.adsb.on.ca/sites/schools/brm/defaul...
3,054542,B28010,Blind River Public School,Public,Elementary,19 Hanes Ave,Blind River,Blind River,Ontario,P0R1B0,705-356-0271,46.18454,-82.9576,705-356-7752,http://www.adsb.on.ca/sites/schools/bli/defaul...
4,490822,B28010,Boreal French Immersion Public School,Public,Elementary,232 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4H6,705-945-7349,46.52447,-84.3107,705-945-7149,http://rosedale.adsb.on.ca/

In [ ]:
School_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   School Number   4915 non-null   object
 1   Board Number    4915 non-null   object
 2   School Name     4915 non-null   object
 3   School Type     4915 non-null   object
 4   School Level    4915 non-null   object
 5   Street          4912 non-null   object
 6   Municipality    4912 non-null   object
 7   City            4912 non-null   object
 8   Province        4912 non-null   object
 9   Postal Code     4912 non-null   object
 10  Fax Number      4479 non-null   object
 11  Latitude        4912 non-null   float64
 12  Longitude       4912 non-null   float64
 13  Phone Number    4699 non-null   object
 14  School Website  4758 non-null   object
dtypes: float64(2), object(13)
memory usage: 576.1+ KB

In [ ]:
Enrolment_path = "Endrolment_Data.csv"

Enrolment_df = pd.read_csv(Enrolment_path)

Enrolment_df.head()

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
0,902344,2019-2020,Public,Secondary,0,0,0,0,0,0,0,0,10,10,30,175,225
1,19186,2019-2020,Public,Elementary,25,15,15,30,15,30,20,10,0,0,0,0,160
2,67679,2019-2020,Public,Elementary,10,10,10,0,0,0,0,0,0,0,0,0,30
3,43362,2019-2020,Public,Elementary,15,20,15,20,15,20,15,10,0,0,0,0,130
4,54542,2019-2020,Public,Elementary,10,10,15,15,25,25,15,30,0,0,0,0,145

In [ ]:
Enrolment_df["School Number"] = Enrolment_df["School Number"].astype(str)

In [ ]:
Enrolment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14692 entries, 0 to 14691
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Number       14692 non-null  object
 1   Year                14692 non-null  object
 2   School Type         14692 non-null  object
 3   School Level        14692 non-null  object
 4   Grade 1 Enrolment   14692 non-null  int64
 5   Grade 2 Enrolment   14692 non-null  int64
 6   Grade 3 Enrolment   14692 non-null  int64
 7   Grade 4 Enrolment   14692 non-null  int64
 8   Grade 5 Enrolment   14692 non-null  int64
 9   Grade 6 Enrolment   14692 non-null  int64
 10  Grade 7 Enrolment   14692 non-null  int64
 11  Grade 8 Enrolment   14692 non-null  int64
 12  Grade 9 Enrolment   14692 non-null  int64
 13  Grade 10 Enrolment  14692 non-null  int64
 14  Grade 11 Enrolment  14692 non-null  int64
 15  Grade 12 Enrolment  14692 non-null  int64
 16  Total Enrolment     14692 non-null  int64
dtypes: int64(13), object(4)
memory usage: 1.9+ MB

In [ ]:
# Merge the two DataFrames on the common ID column with how='inner' to keep only the common rows
common_rows = pd.merge(School_df, Enrolment_df, on='School Number', how='inner')

# Filter the original DataFrames to keep only the common rows
School_df = School_df[School_df['School Number'].isin(common_rows['School Number'])]
Enrolment_df = Enrolment_df[Enrolment_df['School Number'].isin(common_rows['School Number'])]

In [ ]:
School_df.head()

,School Number,Board Number,School Name,School Type,School Level,Street,Municipality,City,Province,Postal Code,Fax Number,Latitude,Longitude,Phone Number,School Website
0,902344,B28010,Algoma Education Connection Secondary School,Public,Secondary,550 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4J4,705-945-7173,46.53477,-84.3077,705-945-7194,http://www.adsb.on.ca
4,490822,B28010,Boreal French Immersion Public School,Public,Elementary,232 Northern Ave,Sault Ste. Marie,Sault Ste Marie,Ontario,P6B4H6,705-945-7349,46.52447,-84.3107,705-945-7149,http://rosedale.adsb.on.ca/
5,137967,B28010,Central Algoma Intermediate School,Public,Elementary,32 Kensington Road,Huron Shores,Desbarats,Ontario,P0R1E0,705-782-4288,46.34007,-83.9369,705-782-6263,http://www.adsb.on.ca/sites/schools/cis/defaul...
6,285552,B28010,Central Algoma Public School,Public,Elementary,5 Margaret St,Johnson,Desbarats,Ontario,P0R1E0,705-782-0260,46.34875,-83.9253,705-782-6233,http://www.adsb.on.ca/content/schools/school_d...
7,891347,B28010,Central Algoma Secondary School,Public,Secondary,32 Kensington Rd,Johnson,Desbarats,Ontario,P0R1E0,705-782-4288,46.33811,-83.9355,705-782-6263,http://www.adsb.on.ca/sites/schools/cas/defaul...

In [ ]:
Enrolment_df.head()

,School Number,Year,School Type,School Level,Grade 1 Enrolment,Grade 2 Enrolment,Grade 3 Enrolment,Grade 4 Enrolment,Grade 5 Enrolment,Grade 6 Enrolment,Grade 7 Enrolment,Grade 8 Enrolment,Grade 9 Enrolment,Grade 10 Enrolment,Grade 11 Enrolment,Grade 12 Enrolment,Total Enrolment
0,902344,2019-2020,Public,Secondary,0,0,0,0,0,0,0,0,10,10,30,175,225
5,490822,2019-2020,Public,Elementary,55,55,40,40,50,35,35,35,0,0,0,0,345
6,137967,2019-2020,Public,Elementary,0,0,0,0,0,0,70,90,0,0,0,0,160
7,285552,2019-2020,Public,Elementary,10,10,10,20,30,25,0,0,0,0,0,0,105
8,891347,2019-2020,Public,Secondary,0,0,0,0,0,0,0,0,90,80,85,90,345

In [ ]:
School_df.to_csv('school_data_final.csv', index=False)

In [ ]:
Enrolment_df.to_csv('enrolment_data_final.csv', index=False)